name: Java CI with Maven - Test and package
on: [push]
jobs:
  Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: SonarConnectTest
        env: 
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
        run: 
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')